config/routes.rb
Rails.application.routes.draw do
  resources :home
	
  get 'home/index'

  get 'home/page/:id/per_page/:per_page', to: 'home#page'

  resources :home do
    member do
      get 'enrollments'
    end
  end  

  root :to => "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def parseLinks(link)
	match = link.scan(/<http:\/\/.*?\?page=([0-9]+)&per_page=([0-9]+)>;\s+rel="(.*?)"/)
	return match
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#default page which shows all the courses
	def index
		api = API.new
		response = api.getCourses();
		if(response)
			@courses = JSON.parse(response.body)
			@links = parseLinks(response.headers['Link'])
		else
			#Do something with error
			@error = api.error_code
			@courses = []
			@links = []
		end
  	
  	end

	#displays data for single course
	def show
		api = API.new
		response = api.getCourse(params[:id])
		if(response)
	  		@course = JSON.parse(response.body)
		else
			#Do something with error
			@error = api.error_code
			@course = {}
		end  
	end

	#shows page by page listing of course
	def page
		api = API.new
		response = api.getCoursePage(params[:page], params[:per_page])
		if(response)
			@courses = JSON.parse(response.body)
			@links = parseLinks(response.headers['Link'])
		else
			#Do something with error
			@error = api.error_code
			@courses = []
			@links = []
		end
		render "index"
	end

	#enroll in a course
	def enrollments
		api = API.new
		response = api.enroll(params[:id])
		if(response)
			@status = JSON.parse(response.body)
		else
			#Do something with error
			@error = api.error_code
			@status = {}
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def parseLinks(link)
		
	end
end

app/views/home/enrollments.html.erb
<div>
<h3><%= @status["type"]%></h3>
<ul>
</ul>

</div>

app/views/home/index.html.erb
<ul>
<% @links.each do |link| %>
	<li>
		<%= link_to link[2], '/home/page/'+link[0]+'/per_page/'+link[1] %>
	</li>
<% end %>
</ul>
<ul>
<% @courses.each do |course| %>
	<li>
		<div>
			<%= link_to course["name"], home_path(course["id"]) %>
		</div>
		<div><%= course["description"] %></div>
		<hr/>
	</li>
<% end %>
</ul>

app/views/home/show.html.erb
<div>
<h3><%= @course["name"]%></h3>
<ul>
	<li>Code:<%=@course["code"]%></li>
	<li>Start At:<%=@course["start_at"]%></li>
</ul>
<p>
	<%=@course["description"]%>
</p>
<p>
	<%= link_to "Enroll", home_path(@course["id"], '/enrollments') %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instructure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>